fix(ObjectPage - TypeScript): fix `accessibilityAttributes` `expandButton.expanded` type (#7891)
Doesn’t throw an error when built here, but if ui5wcr is consumed with
`skipLibCheck: false`, it throws:

```sh
 error TS2339: Property 'expanded' does not exist on type 'ButtonAccessibilityAttributes | undefined'.

104                 expanded?: ButtonPropTypes['accessibilityAttributes']['expanded'] | undefined;
                                                                          ~~~~~~~~~~


Found 1 error in node_modules/@ui5/webcomponents-react/dist/components/ObjectPage/types/index.d.ts:104

```